name: 'Calver Release'
description: 'Automatically create Calver compliant tags or releases based on PR labels'
author: 'Stéphane Bour'

branding:
  icon: 'tag'
  color: 'green'

inputs:
  release_branch:
    description: 'Branch to tag'
    required: false
    default: master
  name:
    description: 'The title of the release'
    required: false
    default: '0'
  message:
    description: 'The message of the release'
    required: false
    default: '0'
  draft:
    description: 'Is draft ?'
    required: false
    default: 'false'
  pre:
    description: 'Is pre-release ?'
    required: false
    default: 'false'
  release:
    description: 'Create new release'
    required: false
    default: 'true'
  date_format:
    description: 'Format date in posix shell'
    required: false
    default: '%Y.%V'

outputs:
  release:
    description: 'The newly created release'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release_branch }}
    - ${{ inputs.name }}
    - ${{ inputs.message }}
    - ${{ inputs.draft }}
    - ${{ inputs.pre }}
    - ${{ inputs.release }}
    - ${{ inputs.date_format }}
